name: PlatformIO Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  platformio-build:
    name: PlatformIO Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: karniv00l/platformio-run-action@v1
